[build]
  # Configura o comando de build (opcional)
  command = "echo 'Iniciando deployment...'"
  
  # CORREÇÃO: Define o diretório raiz (ponto) como o publish directory.
  # Isso impede que o Netlify procure a pasta 'public'.
  publish = "." 

[functions]
  directory = "netlify-functions"

[build.environment]
  AWS_LAMBDA_PYTHON_RUNTIME = "python3.8"
  PIP_REQUIREMENTS = "requirements.txt"
