[build]
  # Define o diretório raiz como o diretório de publicação.
  # Isso impede o erro de 'public' não existe.
  publish = "." 
  # O comando de build é opcional, mas pode ser mantido
  command = "echo 'Iniciando deployment...'"

[functions]
  # Esta linha diz ao Netlify onde procurar sua função 'alerta.py'
  directory = "netlify-functions"

[build.environment]
  # Define o runtime para Python 3.8, que é padrão no Lambda/Netlify
  AWS_LAMBDA_PYTHON_RUNTIME = "python3.8"
  # Nome do seu arquivo de dependências
  PIP_REQUIREMENTS = "requirements.txt"